org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-17.0.17.10-hotspot
android.userHome=C:/Users/Administrator/My Shop/.android_cache
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.mpp.enableIntrinsicTransitions=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
org.jetbrains.compose.experimental.jscanvas.enabled=true
