org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -Duser.home=C:/Users/Administrator/My_Shop_Home
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-17.0.17.10-hotspot
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.mpp.enableIntrinsicTransitions=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
org.jetbrains.compose.experimental.jscanvas.enabled=true
